apps/accounting/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", sessions: "users/sessions"}, skip: [:registrations]

  resources :transactions, only: [:index, :show]
  resources :users, only: [:index, :show]
  resources :billing_cycles, only: [:index, :show] do
    collection do
      post :close
    end
  end

  root to: redirect("/billing_cycles")

  get 'up' => 'rails/health#show', as: :rails_health_check
end

apps/accounting/app/models/billing_cycle.rb
# == Schema Information
#
# Table name: billing_cycles
#
#  id         :bigint           not null, primary key
#  name       :string           default(""), not null
#  user_id    :bigint           not null
#  current    :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class BillingCycle < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :restrict_with_exception

  scope :current, -> { where(current: true) }
  scope :ordered, -> { order(created_at: :desc) }

  default_scope { ordered }

  def balance = transactions.sum(Arel.sql("debit - credit"))

  def as_event_data
    {
      user_id: user.public_id,
      name: name,
      amount: balance
    }
  end
end

apps/accounting/app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id             :bigint           not null, primary key
#  subject        :string           not null
#  assignee_id    :bigint
#  completed_at   :datetime
#  assign_price   :integer
#  complete_price :integer
#  public_id      :string           not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class Task < ApplicationRecord
  belongs_to :assignee, class_name: "User"

  def priced? = complete_price.present? || assign_price.present?

  def self.create_or_update_from_event(data)
    assignee = User.create_or_update_from_event("public_id" => data["assignee_id"])

    params = {
      "subject" => "",
      **data.slice(*column_names).except("assignee_id", "public_id"),
      "assignee" => assignee
    }

    record = create_with(params).create_or_find_by!(public_id: data["public_id"])
    record.update!(params)

    record
  end
end

apps/accounting/app/models/transaction.rb
# == Schema Information
#
# Table name: transactions
#
#  id               :bigint           not null, primary key
#  billing_cycle_id :bigint           not null
#  description      :string           default(""), not null
#  debit            :integer          default(0), not null
#  credit           :integer          default(0), not null
#  public_id        :string           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Transaction < ApplicationRecord

  enum transaction_type: {
    task_assigned: "task.assigned",
    task_completed: "task.completed"
  }

  belongs_to :billing_cycle
  has_one :user, through: :billing_cycle

  scope :ordered, -> { order(created_at: :desc) }

  default_scope { ordered }

  after_initialize :set_public_id, if: :new_record?

  validates :debit, :credit, numericality: { greater_than_or_equal_to: 0 }

  def display_name
    jira_id.presence || subject
  end

  def as_event_data
    {
      user_id: billing_cycle.user.public_id,
      public_id: public_id,
      transaction_type: transaction_type,
      description: description,
      credit: credit,
      debit: debit
    }
  end

  def self.report(transactions)
    transactions
      .select("sum(credit - debit)")
      .group("date_trunc('hour', created_at)")
  end
end

apps/accounting/app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id         :bigint           not null, primary key
#  name       :string           default(""), not null
#  role       :string
#  public_id  :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  provider   :string
#  uid        :string
#
class User < ::ApplicationRecord
  include UserConcern

  has_many :billing_cycles, dependent: :restrict_with_exception
  has_many :transactions, through: :billing_cycles

  has_one :current_billing_cycle,
          -> { where(current: true) },
          inverse_of: :user,
          class_name: "BillingCycle",
          dependent: :restrict_with_exception

  def balance
    current_billing_cycle&.transactions&.sum("debit - credit") || 0
  end
end

apps/accounting/app/controllers/billing_cycles_controller.rb
##
class BillingCyclesController < ApplicationController
  load_and_authorize_resource

  def index
    @grid = BillingCyclesGrid.new { @billing_cycles }
  end

  def show

  end

  def close
    @billing_cycles.find_each do |cycle|
      BillingCycle::Close.run!(billing_cycle: cycle)
    end

    redirect_back fallback_location: root_path, notice: @billing_cycles.size
  end
end

apps/accounting/app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  load_and_authorize_resource

  def index
    @grid = TransactionsGrid.new { @transactions }
  end

  def show
  end
end

apps/accounting/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def doorkeeper
    user = User.from_omniauth(request.env['omniauth.auth'])

    if user.present?
      sign_out_all_scopes
      sign_in :user, user
      redirect_to root_path
    else
      redirect_to new_user_session_path
    end
  end
end

apps/accounting/app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @grid = UsersGrid.new { @users }
  end

  def show
  end
end

apps/accounting/app/views/billing_cycles/index.html.slim
= render "shared/nav"

- if can?(:close, BillingCycle)
  .mb-2
    .d-inline-block
      = form_tag close_billing_cycles_path, method: :post do
        = submit_tag "Выдать зарплату", class: "btn btn-warning"

- count = BillingCycle.where(current: false).count
- if count > 0
  p Уже устали выдавать зарплату (выдали #{count})

= render_grid @grid

apps/accounting/app/views/billing_cycles/show.html.slim
= render "shared/nav"

h1= @billing_cycle.display_name

= show_for @billing_cycle do |bc|
  = bc.attribute :name
  = bc.attribute :balance
  = bc.association :transactions do |t|
    p= [t.debit, t.credit, t.description]

apps/accounting/app/views/shared/_nav.html.slim
ul.nav.nav-tabs.mb-3
  li class="nav-item"
    a href="#{transactions_path}" class="nav-link #{"active" if current_page?(transactions_path)}"
      = Transaction.model_name.human

  li class="nav-item"
    a href="#{billing_cycles_path}" class="nav-link #{"active" if current_page?(billing_cycles_path)}"
      = BillingCycle.model_name.human

apps/accounting/app/views/transactions/index.html.slim
= render "shared/nav"

= render_grid @grid

apps/accounting/app/views/transactions/show.html.slim
h1= @transaction.display_name

= show_for @transaction do |t|
  = t.attribute :id
  = t.attribute :description
  = t.attribute :user do
    = @transaction.user.display_name
  = t.attribute :credit
  = t.attribute :debit
  = t.attribute :created_at

apps/accounting/app/views/users/show.html.slim
h1= @user.display_name

= show_for @user do |t|
  = t.attribute :id
  = t.attribute :name
  = t.attribute :role