apps/tasks/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", sessions: "users/sessions"}, skip: [:registrations]

  resources :tasks, except: [:destroy] do
    member do
      patch :complete
    end

    collection do
      patch :reassign
      patch :mass_complete
      patch :mass_create
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check

  root "tasks#index"
end

apps/tasks/app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id           :bigint           not null, primary key
#  subject      :string           not null
#  assignee_id  :bigint
#  completed_at :datetime
#  public_id    :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Task < ApplicationRecord
  belongs_to :assignee, class_name: "User"

  before_validation do
    self.jira_id ||= begin
                       match = subject.match(/\[(.*)\]/)
                       if match
                         match[1]
                       else
                         ""
                       end
                     end

    self.subject = subject.gsub(/\[.*\]/, "").strip
  end

  scope :completed, -> { where.not(completed_at: nil) }
  scope :not_completed, -> { where(completed_at: nil) }

  scope :ordered, -> { order(created_at: :desc) }

  default_scope { ordered }

  after_initialize :set_public_id, if: :new_record?

  after_commit(on: :create) do
    EDA.stream Task::Created.new(as_event_data)
    EDA.stream Task::Created.new(as_event_data, version: 1) # TODO: убрать после миграции события
  end

  after_commit(on: :update) do
    EDA.stream Task::Updated.new(as_event_data)
    EDA.stream Task::Updated.new(as_event_data, version: 1) # TODO: убрать после миграции события
  end

  def completed? = completed_at.present?

  def as_event_data
    {
      public_id: public_id,
      assignee_id: assignee.public_id,
      completed_at: completed_at,
      subject: subject,
      jira_id: jira_id,
    }
  end
end

apps/tasks/app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id         :bigint           not null, primary key
#  name       :string           default(""), not null
#  role       :string
#  public_id  :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class User < ApplicationRecord
  include UserConcern

  has_many :tasks, inverse_of: :assignee, dependent: :restrict_with_exception
end

apps/tasks/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource

  def index
    @grid = TasksGrid.new { @tasks.includes(:assignee) }
    @not_completed_tasks = @tasks.not_completed
  end

  def show
  end

  def create
    task = AddTask.run!
    EDA.stream Task::Added.new(task.as_event_data)

    redirect_back fallback_location: tasks_path
  end

  def complete
    task = CompleteTask.run!(task: params[:id])
    EDA.stream Task::Completed.new(task.as_event_data)

    redirect_back fallback_location: tasks_path
  end

  def reassign
    ReassignTasks.run!
    redirect_back fallback_location: tasks_path
  end

  def mass_complete
    Task::MassComplete.run!
    redirect_back fallback_location: tasks_path
  end
  def mass_create
    Task::MassCreate.run!
    redirect_back fallback_location: tasks_path
  end
end

apps/tasks/app/views/layouts/application.html.erb
<!doctype html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>aTES</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <style>
    body {
      background: #fafafa;
      padding-bottom: 2em;
    }

    .topnav {
      display: block;
      padding: 1em 0;
      /*border-bottom: 2px solid #aaa;*/
    }

    .topnav__container {
      display: flex;
    }

    .topnav__logotype {
      flex: 0 1 6em;
    }

    .topnav__navigation {
      flex: 1;
    }

    .topnav__user {
      flex: 0 1 200px;
      text-align: right;
    }

    .topnav__user form {
      display: inline;
    }

    .logotype {
      display: inline;
      font-size: 1.35em;
      font-weight: bold;
      margin: 0;
      padding: 0;
    }

    .nav {
      list-style: none;
      padding: 0;
      margin: 0;
    }

    .nav li {
      display: inline-block;
      padding: 0;
      margin-right: 2em;
    }

    .nav a {
      text-decoration: none;
      border-bottom: 2px solid #f5f5f5;
    }

    .nav a:hover {
      border-bottom-color: rgba(var(--bs-link-color-rgb));
    }

    .nav a.active {
      color: seagreen;
      border-bottom-color: var(--bs-green);
      text-decoration: none;
    }

    h1, h2, h3 {
      font-weight: bold;
    }

    table {
      width: 100%;
    }

    table th,
    table td {
      text-align: left;
      border-collapse: collapse;
      border-bottom: 1px solid #eee;
      padding: .5em 1em;
    }

    .card {
      border: none;
    }
  </style>
</head>
<body>

<div class="topnav">
  <div class="topnav__container container">
    <div class="topnav__logotype">
      <h1 class="logotype">aTES</h1>
    </div>
    <div class="topnav__navigation">
      <% if user_signed_in? %>
        <ul class="nav">
          <li>💰&nbsp;<%= link_to "Бухгалтерия", "https://accounting.popuges.easing.ru", class: ("active" if request.url.start_with?("https://accounging.popuges.easing.ru")) %></li>
          <li>🪵&nbsp;<%= link_to "Задачи", "https://tasks.popuges.easing.ru", class: ("active" if request.url.start_with?("https://tasks.popuges.easing.ru")) %></li>
          <li>📉&nbsp;<%= link_to "Аналитика", "https://analytics.popuges.easing.ru", class: ("active" if request.url.start_with?("https://analytics.popuges.easing.ru")) %></li>
          <li>🔥&nbsp;<%= link_to "Уведомления", "https://notifications.popuges.easing.ru", class: ("active" if request.url.start_with?("https://notifications.popuges.easing.ru")) %></li>
          <li>🦜&nbsp;<%= link_to "Попуги", "https://auth.popuges.easing.ru", class: ("active" if request.url.start_with?("https://auth.popuges.easing.ru")) %></li>
        </ul>
      <% end %>
    </div>

    <div class="topnav__user">
      <% if user_signed_in? %>
        <strong>
          <%= link_to current_user.name, "https://auth.popuges.easing.ru/users/#{current_user.id}" %>
        </strong>
        &nbsp;
        <%= form_for current_user, method: :delete, url: destroy_user_session_url do %>
          <input type="submit" value="Выйти"/>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="card">
    <div class="card-body">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

apps/tasks/app/views/tasks/index.html.slim
h1 В работе <code>#{@not_completed_tasks.count}</code> или около. Трудятся #{User.role_popug.count} 🦜

- if can?(:reassign, Task) || can?(:create, Task)
  .pt-2.pb-3
    - if can?(:create, Task)
      .d-inline-block
        = form_tag tasks_path, method: :post do |f|
          = submit_tag "Добавить задачу", class: "btn btn-outline-success"
      .d-inline-block &nbsp;&nbsp;&nbsp;

    - if can?(:mass_create, Task)
      .d-inline-block
        = form_tag mass_create_tasks_path, method: :patch, style: "display: inline;" do |f|
          = submit_tag "Всем по задаче", class: "btn btn-outline-primary"
      .d-inline-block &nbsp;&nbsp;&nbsp;

    - if can?(:reassign, Task)
      .d-inline-block
        = form_tag reassign_tasks_path, method: :patch, style: "display: inline;" do |f|
          = submit_tag "Перемешать", class: "btn btn-outline-secondary"
      .d-inline-block &nbsp;&nbsp;&nbsp;

    - if can?(:mass_complete, Task)
      .d-inline-block
        = form_tag mass_complete_tasks_path, method: :patch, style: "display: inline;" do |f|
          = submit_tag "Закрыть пачку", class: "btn btn-warning"



= render_grid @grid

apps/tasks/app/views/tasks/show.html.slim
h1= @task.display_name

= show_for @task do |t|
  = t.attribute :id
  = t.attribute :public_id
  = t.attribute :subject
  = t.attribute :assignee do
    = @task.assignee.display_name
  = t.attribute :completed_at
  = t.attribute :created_at
  = t.attribute :updated_at